export const TRV_REASON_CODES: Record<string, string> = {
    // 2.1 Driftledningsorsaker (D)
    "D OG": "Ordergivning pga. Tågföring",
    "D OS": "Operativa stödsystem",
    "D OS 2": "Administrativt stödsystem",
    "D OS 3": "Avläsningsfel",
    "D PR": "Prioritering",
    "D PR 3": "Operativ prioritering",
    "D PR 4": "Operativ ledning prioriterar",
    "D PS": "Personal",
    "D PS 1": "Driftledningspersonal",
    "D PS 2": "Driftledningspersonal resursbrist",
    "D PS 4": "Operativ ledning",
    "D PS 5": "Operativ ledning resursbrist",
    "D PS 6": "Orsaksutredning",
    "D TT": "Misstänkt fel i körplan/ felplanering",
    "D TT 1": "Operativa riktlinjer",

    // 2.2 Följdorsaker (F)
    "F AT": "Stört av annat tåg",
    "F OI": "Omlopp/inväntan",
    "F OI 3": "Omlopp personal",
    "F OI 5": "Omlopp/Tåglänk",
    "F OI 7": "Omlopp lok",
    "F OI 8": "Omlopp vagn",
    "F TF": "Tågföring",
    "F TF 1": "Möte/Korsande tågväg",
    "F TF 2": "Förbigång",
    "F TF 3": "Tåg före/Spårbrist",

    // 2.3 Infrastrukturorsaker (I)
    "I AK": "Avgrävd kabel",
    "I AK 1": "Avgrävd signalkabel",
    "I AK 2": "Avgrävd telekommunikationskabel",
    "I AK 3": "Avgrävd elkabel",
    "I BA": "Bangårdsanläggningar",
    "I BA 1": "Bangårdsbelysning och plattformsbelysning",
    "I BA 2": "Plattform och lastkaj",
    "I BA 3": "Plattformsövergång",
    "I BA 4": "Rangerbromssystem",
    "I BA 5": "Spårspärr",
    "I BA 6": "Stoppbock",
    "I BA 7": "Bromsprovanläggning",
    "I BA 8": "Tåg- och lokvärmeanläggning",
    "I BA 9": "Vagnvåg",
    "I BA 10": "Vändskiva",
    "I BA 11": "Vattenpost",
    "I BT": "Planerat Banarbete/transport",
    "I BT 20": "Förplanerat överskridet banarbete",
    "I BT 21": "Underhåll",
    "I BT 22": "Investering",
    "I BT 23": "Stora projekt",
    "I BT 24": "Planering",
    "I BT 30": "Direktplanerat trafikstörande banarbete",
    "I BT 40": "Förseningar med anledning av planerat banarbete",
    "I BU": "Banunderbyggnad",
    "I BU 1": "Bank",
    "I BU 2": "Skärning",
    "I BU 3": "Trumma",
    "I BU 4": "Bro",
    "I BU 5": "Tunnel",
    "I BÖ": "Banöverbyggnad",
    "I BÖ 1": "Spår",
    "I BÖ 2": "Spårväxel",
    "I BÖ 3": "Skymd sikt på grund av vegetation",
    "I EA": "Elanläggningar",
    "I EA 1": "Kontaktledning",
    "I EA 2": "Hjälpkraftledning",
    "I EA 3": "Fördelningsstation",
    "I EA 4": "Kopplingscentral",
    "I EA 5": "Matarledning",
    "I EA 6": "Frånskiljarstation",
    "I EA 7": "Nätstation",
    "I EA 8": "Omformarstation",
    "I EA 9": "Sektioneringsstation",
    "I EA 10": "Transformatorstation",
    "I EA 11": "Eldriftledningssystem",
    "I EA 12": "Teknikbyggnad",
    "I EA 13": "Extern elleverantör",
    "I FK": "Framkomlighet i spår pga. Väder",
    "I FK 1": "Verifierad spårhalka",
    "I FK 2": "Snö och is",
    "I FK 3": "Träd",
    "I SA": "Signalanläggningar",
    "I SA 1": "Balisgrupp",
    "I SA 2": "Plankorsning",
    "I SA 3": "Positioneringssystem",
    "I SA 4": "Signal",
    "I SA 5": "Signalställverk, RBC och linjeblockeringssystem",
    "I SA 6": "Rangerställverk",
    "I SA 7": "Tavla",
    "I SA 8": "Tågledningssystem – SNTL",
    "I SA 10": "Tågledningssystem - EBICOS 900",
    "I SA 12": "Tågledningssystem – ERTMS",
    "I SA 15": "Central automatik",
    "I SA 16": "Digital graf/STEG/AEF",
    "I SA 17": "Lokala automater",
    "I TA": "Teleanläggningar",
    "I TA 1": "Detektor",
    "I TA 8": "Dynamisk skylt",
    "I TA 9": "Högtalarsystem",
    "I TA 10": "Klockor",
    "I TA 11": "Operativ telefoni (MATS)",
    "I TA 12": "Kabelanläggning – Telekabel (opto eller koppar)",
    "I TA 13": "Tågradio MobiSIR",
    "I TA 14": "Teletransmission/Datakommunikation",
    "I TA 15": "Dataställverk",
    "I ÖA": "Övriga anläggningar",
    "I ÖA 1": "Fastighet",
    "I ÖA 2": "Hägnad",
    "I ÖA 3": "Kanalisation",
    "I ÖA 4": "Rälssmörjningsapparat",
    "I ÖA 5": "Snögalleri",
    "I ÖA 7": "Avvattning, pumpsystem",
    "I ÖA 8": "Övervakningskamera",

    // 2.4 Järnvägsföretagsorsaker (J)
    "J AS": "Avvikande sammansättning",
    "J AS 1": "Överskjutande lastprofil/Specialtransport",
    "J AS 2": "Ej planenlig tåglängd",
    "J AS 3": "Ej planenlig tågvikt",
    "J AS 6": "Ej planenlig/avvikande STH",
    "J AS 7": "Farligt gods",
    "J DM": "Dragfordon / motorvagn",
    "J DM 1": "ATC/ETCS-fel",
    "J DM 3": "Strömavtagare",
    "J DM 4": "Hjulskadelarm",
    "J DM 5": "Bromsfel/Bromssystem/Tjuvbromslarm",
    "J DM 6": "Omstart/Återställning system",
    "J DM 9": "Dörrfel",
    "J DM 10": "Tyfon",
    "J DM 11": "Akut felavhjälpning",
    "J DM 12": "Varmgångslarm",
    "J IA": "Innan avgång",
    "J IA 1": "Städ",
    "J IA 2": "Lastning/Lossning",
    "J IA 4": "Verkstadsåtgärd",
    "J IA 5": "Tågsättsbyte",
    "J IA 6": "Tåg ej klargjort/färdigställt",
    "J IA 7": "Sen växling av entreprenör",
    "J IA 8": "Inväntade vagnar från kund",
    "J IA 9": "Sen rapport av kundcenter",
    "J IA 10": "Sena uppgifter från operativt center",
    "J IA 11": "Fel på IT-system",
    "J IA 13": "Växlingslok saknas",
    "J PR": "Prioritering",
    "J PR 1": "Ett järnvägsföretag har bestämt prioritering mellan egna tåg",
    "J PR 2": "Två järnvägsföretag har bestämt prioritering mellan varandras tåg",
    "J PR 3": "Inväntan",
    "J PR 4": "Växling/Rangering utöver plan",
    "J PR 5": "Oplanerad sammansättning",
    "J PR 6": "Omloppsändring",
    "J PR 7": "Extra beställning av tågläge",
    "J PR 8": "Extra uppehåll begärt",
    "J PR 9": "Furnering",
    "J PR 10": "Växlingsrörelse i vägen",
    "J PS": "Personal",
    "J PS 1": "Förarpersonal",
    "J PS 2": "Stationär personal",
    "J PS 3": "Ombordpersonal",
    "J PS 4": "Handhavandefel",
    "J PS 5": "Otillåten stoppassage A",
    "J RU": "Resandeutbyte",
    "J RU 1": "Stor resenärsvolym",
    "J RU 2": "Av-/pålastning av tillgänglighetsanpassad utrustning",
    "J RU 3": "Av-/pålastning av personlig specialutrustning",
    "J VA": "Vagn",
    "J VA 1": "Dörrfel",
    "J VA 2": "Bromsfel/Bromssystem/Tjuvbromslarm",
    "J VA 3": "Hjulskadelarm",
    "J VA 4": "Lastförskjutning/Fellastning/Lastjustering",
    "J VA 5": "Självavkoppling/Avslitet tåg",
    "J VA 6": "Vagnssyn",
    "J VA 7": "Skada vagn/Akut felavhjälpning",
    "J VA 8": "Varmgångslarm",

    // 2.5 Olyckor och tillbud (O)
    "O BÖ": "Broöppning",
    "O BÖ 1": "Broöppningstid överskriden",
    "O BÖ 2": "Planerad broöppning",
    "O DJ": "Djur",
    "O DJ 1": "Påkört vilt",
    "O DJ 2": "Levande vilt i spårområdet",
    "O DJ 3": "Påkörd ren",
    "O DJ 4": "Påkört tamdjur",
    "O DJ 5": "Levande tamdjur i spårområdet",
    "O MÄ": "Människa",
    "O MÄ 1": "Påkörd person",
    "O MÄ 2": "Obehöriga i spåret",
    "O MÄ 3": "Polis/Akut sjukdom/Avhysning/Hotfull situation",
    "O MÄ 4": "Sabotage/Hot",
    "O MÄ 5": "Suicidial",
    "O NA": "Naturhändelser",
    "O NA 1": "Brand",
    "O NA 2": "Översvämning",
    "O NA 3": "Storm/Snöstorm",
    "O NA 4": "Lavin",
    "O NA 5": "Skred",
    "O NA 6": "Kyla",
    "O NA 7": "Spårhalka",
    "O NA 8": "Fåglar",
    "O NA 9": "Träd",
    "O NA 10": "Åska/Blixt",
    "O NK": "Allvarlig incident, kris och fara",
    "O NK 1": "Pandemi",
    "O NK 2": "Terrordåd",
    "O ST": "Strejk",
    "O ST 1": "Planerad strejk",
    "O ST 2": "Oplanerad strejk",
    "O SY": "Avsyning av bana/fordon",
    "O SY 1": "Avsyning av bana",
    "O SY 2": "Avsyning av fordon",
    "O TÅ": "Tåg/arbetsrörelse",
    "O TÅ 1": "Urspårning/Kollision",
    "O TÅ 2": "Plankorsningsolycka",
    "O TÅ 3": "ATC-nödbroms",
    "O TÅ 5": "Uppkörd växel",
    "O TÅ 6": "Provkörning/Testtåg",
    "O UT": "Sent till/från utland",
    "O UT 1": "Gränskontroll",
    "O UT 2": "På begäran av utländsk myndighet",
    "O UT 3": "Annan infrastrukturförvaltare/fastighetsförvaltare",

    // 2.6 Ytterligare utredning (Y)
    "Y UK": "Ytterligare utredning krävs"
};
